import type { Metadata } from 'next'
import { FC } from 'react';
import { Nav } from '../../components/Nav'
import { Col, Layout, Row } from 'antd';
import { Content, Footer, Header } from 'antd/es/layout/layout';
import { HeaderProfile } from '../../components/HeaderProfile';
import { Providers } from '../../components/Providers';
import './globals.css'

// const { Header, Footer, Sider, Content } = Layout;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface IRootLayoutProps {
  pageProps: object,
  children: React.ReactNode,
  params: { language: string }
}

const RootLayout: FC<IRootLayoutProps> = ({
  children,
  params: {
    language
  }
}) => {
  return (
    <html className='min-h-full flex flex-col'>
      <body className='min-h-full grow flex'>
        <Providers locale={language}>
          <Layout className='min-h-full grow'>
            <Header className='flex items-center'>
              <div className='flex flex-grow'>
                <span>Привет</span>
                <Nav language={language} />
              </div>
              <HeaderProfile />
            </Header>
            <Content className='px-10 py-6'>
              <Row gutter={{ xl: 20 }}>
                <Col
                  xxl={{
                    span: 11,
                    offset: 3
                  }}
                  xl={{
                    span: 17,
                  }}
                  xs={{
                    span: 24,
                  }}
                >
                  {children}
                </Col>
                <Col
                  xl={{
                    span: 6,
                  }}
                  xs={{
                    span: 0,
                  }}
                  style={{ background: 'blue' }}>
                  <div>sidebar</div>
                </Col>
              </Row>
            </Content>
            <Footer style={{ textAlign: 'center' }}>
              Ant Design ©{new Date().getFullYear()} Created by Ant UED
            </Footer>
          </Layout>
        </Providers>
      </body>

    </html>
  )
}

export default RootLayout;
